### PR TITLE
Avoid union

### PR DESCRIPTION
**Pull request by amontoison**
@bjarthur 
I did a few modifications such that we don't use `Union{Nothing,CuMatrix{Cint}}`.

### CODE REVIEW

**Comment by bjarthur** [comment]
why do you think a binary Union is bad?  my understanding is that the julia compiler deals with it quite well-- it just specializes on which ever one it is.  am i wrong about that?

or is it that you want a simpler API with one less input argument, so the user doesn't have to specify `nothing` for `pivotArray`.  if that's the case, then what would you think of modifying my original PR to have that be a keyword argument instead with a default value of nothing?

these changes would also almost double the lines of code: 2045-1890=155 lines of code vs. 1971-1890=81.

all that being said, i don't have super strong feelings either way, so will happily merge if that's what you want.

**Comment by amontoison** [comment]
> why do you think a binary Union is bad? my understanding is that the julia compiler deals with it quite well-- it just specializes on which ever one it is. am i wrong about that?
> 
> or is it that you want a simpler API with one less input argument, so the user doesn't have to specify `nothing` for `pivotArray`. if that's the case, then what would you think of modifying my original PR to have that be a keyword argument instead with a default value of nothing?

Sorry for not answering earlier. 
Yes, I would like the user to not specify `nothing`.
Let use a keyword argument for `pivotArray`.
 
> these changes would also almost double the lines of code: 2045-1890=155 lines of code vs. 1971-1890=81.
> 
> all that being said, i don't have super strong feelings either way, so will happily merge if that's what you want.

With your suggestion, it should fix this problem.

**Comment by bjarthur** [comment]
i've refactored the code to make `pivotArray` an *optional* argument.  we had discussed a keyword argument but optional is even more succinct.

to boot, the code is now specialized on the type of `pivotArray`, so the `isnothing` switch is elided in the compiled code.

i've closed this commit and pushed the changes to https://github.com/JuliaGPU/CUDA.jl/pull/2385

**Comment by bjarthur** [comment]
@amontoison just noticed your thumbs up.  if you're happy with this PR now, could you please merge?  thanks!

**Comment by amontoison** [comment]
Done :smiley:

**Pull request closed without merging**
